"""Transport client protocol for Clawd Tank daemon."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class TransportClient(Protocol):
    """Interface shared by BLE and simulator TCP transports."""

    @property
    def is_connected(self) -> bool: ...

    async def connect(self) -> None: ...

    async def disconnect(self) -> None: ...

    async def ensure_connected(self) -> None: ...

    async def write_notification(self, payload: str) -> bool: ...

    async def read_config(self) -> dict: ...

    async def write_config(self, payload: str) -> bool: ...
