#!/usr/bin/env python3
"""
PNG to RGB565 Converter for ESP32 LCD sprites.

Converts PNG frames to C header files with RGB565 pixel data.
Transparent pixels (alpha < 128 or matching #1a1a2e) use key color 0x18C5.

Usage:
    python tools/png2rgb565.py input_dir output_header --name array_prefix

Example:
    python tools/png2rgb565.py sprites/idle firmware/main/idle_frames.h --name idle
"""

import argparse
import os
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required. Install it with:")
    print("  pip install Pillow")
    sys.exit(1)

# Transparency key color in RGB565
TRANSPARENT_KEY = 0x18C5

# Background color to treat as transparent (#1a1a2e)
BG_COLOR = (0x1A, 0x1A, 0x2E)


def rgb_to_565(r, g, b):
    """Convert 8-bit RGB to RGB565."""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def is_transparent(r, g, b, a):
    """Check if a pixel should be treated as transparent."""
    if a < 128:
        return True
    if (r, g, b) == BG_COLOR:
        return True
    return False


def convert_png_to_rgb565(image_path):
    """Convert a PNG image to a list of RGB565 values."""
    img = Image.open(image_path).convert("RGBA")
    width, height = img.size
    pixels = []

    for y in range(height):
        for x in range(width):
            r, g, b, a = img.getpixel((x, y))
            if is_transparent(r, g, b, a):
                pixels.append(TRANSPARENT_KEY)
            else:
                val = rgb_to_565(r, g, b)
                # Avoid accidental collision with transparent key
                if val == TRANSPARENT_KEY:
                    val = TRANSPARENT_KEY + 1
                pixels.append(val)

    return pixels, width, height


def format_pixel_array(pixels, name, indent="    "):
    """Format pixel data as a C array."""
    lines = []
    for i in range(0, len(pixels), 16):
        chunk = pixels[i:i + 16]
        hex_vals = ", ".join(f"0x{v:04X}" for v in chunk)
        lines.append(f"{indent}{hex_vals},")
    return "\n".join(lines)


def generate_header(frames_data, prefix, width, height):
    """Generate a complete C header file."""
    guard = f"{prefix.upper()}_FRAMES_H"
    frame_count = len(frames_data)

    lines = []
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append("/**")
    lines.append(f" * Auto-generated by png2rgb565.py")
    lines.append(f" * {frame_count} frame(s), {width}x{height} pixels, RGB565")
    lines.append(f" * Transparent key: 0x{TRANSPARENT_KEY:04X}")
    lines.append(" */")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define {prefix.upper()}_WIDTH  {width}")
    lines.append(f"#define {prefix.upper()}_HEIGHT {height}")
    lines.append(f"#define {prefix.upper()}_FRAME_COUNT {frame_count}")
    lines.append(f"#define {prefix.upper()}_TRANSPARENT_KEY 0x{TRANSPARENT_KEY:04X}")
    lines.append("")

    # Individual frame arrays
    for i, pixels in enumerate(frames_data):
        lines.append(f"static const uint16_t {prefix}_frame_{i:02d}[{width * height}] = {{")
        lines.append(format_pixel_array(pixels, prefix))
        lines.append("};")
        lines.append("")

    # Frame table
    lines.append(f"static const uint16_t* const {prefix}_frames[{frame_count}] = {{")
    for i in range(frame_count):
        comma = "," if i < frame_count - 1 else ""
        lines.append(f"    {prefix}_frame_{i:02d}{comma}")
    lines.append("};")
    lines.append("")
    lines.append(f"#endif // {guard}")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Convert PNG frames to RGB565 C header"
    )
    parser.add_argument("input_dir", help="Directory containing PNG frames")
    parser.add_argument("output_header", help="Output C header file path")
    parser.add_argument(
        "--name", required=True, help="Array name prefix (e.g., 'idle')"
    )
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    if not input_dir.is_dir():
        print(f"Error: {input_dir} is not a directory")
        sys.exit(1)

    # Find PNG files sorted alphabetically
    png_files = sorted(input_dir.glob("*.png"))
    if not png_files:
        print(f"Error: No PNG files found in {input_dir}")
        sys.exit(1)

    print(f"Found {len(png_files)} PNG file(s) in {input_dir}")

    frames_data = []
    width, height = None, None

    for png_file in png_files:
        pixels, w, h = convert_png_to_rgb565(png_file)
        if width is None:
            width, height = w, h
        elif (w, h) != (width, height):
            print(f"Warning: {png_file.name} is {w}x{h}, expected {width}x{height}. Skipping.")
            continue

        frames_data.append(pixels)
        print(f"  Converted: {png_file.name} ({w}x{h}, {len(pixels)} pixels)")

    if not frames_data:
        print("Error: No valid frames converted")
        sys.exit(1)

    # Generate header
    header = generate_header(frames_data, args.name, width, height)

    # Write output
    output_path = Path(args.output_header)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header)

    print(f"\nGenerated: {output_path}")
    print(f"  Prefix: {args.name}")
    print(f"  Frames: {len(frames_data)}")
    print(f"  Size: {width}x{height}")
    print(f"  Transparent key: 0x{TRANSPARENT_KEY:04X}")


if __name__ == "__main__":
    main()
